baseurl = "https://store712.tn"
disableLanguages = []
googleAnalytics = "UA-214869998-1"
summarylength = "20"
theme = "vex-hugo"
title = "Store712 | Mode de luxe pour hommes et femmes"
[Languages.en]
contentDir = "content/english"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = ""
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[markup.goldmark.renderer]
unsafe = true
[[menu.footer]]
name = "Blog"
url = "blog"
weight = 1
[[menu.footer]]
name = "Contact"
url = "contact"
weight = 2
[[menu.footer]]
name = "Terms & Conditions"
url = "terms-conditions"
weight = 3
[[menu.footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 4
[[menu.main]]
name = "Acceuil"
url = "/"
weight = 1
[[menu.main]]
name = "Produits"
url = "products"
weight = 2
[[menu.main]]
name = "Blog"
url = "blog"
weight = 3
[[menu.main]]
name = "Review"
pre = "#"
url = "testimonial"
weight = 4
[[menu.main]]
name = "Contact"
url = "contact"
weight = 5
[params]
author = "Store712"
contact_form_action = "#"
currency = "TND"
description = "Portez des grandes marques et labels de mode émergents sur Store712.  Livraison a domicile."
logo = "images/logo2.png"
logo_width = "100px"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.css]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.css"
[[params.plugins.js]]
link = "plugins/jquery/jquery-3.6.0.slim.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.js"
[params.preloader]
enable = false
preloader = ""
[params.snipcart]
enable = false
snipcart_api = ""
[params.subscription]
mailchimp_form_action = ""
mailchimp_form_name = ""
